const POLICY_DATA = {
  "rows": [
    {
      "bundle": "인터넷 단품",
      "internet": "에센스",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 10.0,
      "kosGift": 5.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "베이직",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 6.0,
      "kosGift": 4.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "슬림플러스↓",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 2.0,
      "kosGift": 4.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "슬림",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 1.0,
      "kosGift": 4.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "에센스",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 17.0,
      "kosGift": 5.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "베이직",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 13.0,
      "kosGift": 4.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "슬림플러스↓",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 9.0,
      "kosGift": 4.0
    },
    {
      "bundle": "인터넷 단품",
      "internet": "슬림",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 8.0,
      "kosGift": 4.0
    },
    {
      "bundle": "M+I",
      "internet": "에센스",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 24.0,
      "kosGift": 5.0
    },
    {
      "bundle": "M+I",
      "internet": "베이직",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 16.0,
      "kosGift": 4.0
    },
    {
      "bundle": "M+I",
      "internet": "슬림플러스↓",
      "tv": null,
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 10.0,
      "kosGift": 4.0
    },
    {
      "bundle": "M+I",
      "internet": "에센스",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 5.0
    },
    {
      "bundle": "M+I",
      "internet": "베이직",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 23.0,
      "kosGift": 4.0
    },
    {
      "bundle": "M+I",
      "internet": "슬림플러스↓",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 17.0,
      "kosGift": 4.0
    },
    {
      "bundle": "U+I",
      "internet": "에센스",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 5.0
    },
    {
      "bundle": "U+I",
      "internet": "베이직",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 23.0,
      "kosGift": 4.0
    },
    {
      "bundle": "U+I",
      "internet": "슬림플러스↓",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 17.0,
      "kosGift": 4.0
    },
    {
      "bundle": "U+I",
      "internet": "에센스",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 5.0
    },
    {
      "bundle": "U+I",
      "internet": "베이직",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 23.0,
      "kosGift": 4.0
    },
    {
      "bundle": "U+I",
      "internet": "슬림플러스↓",
      "tv": null,
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 17.0,
      "kosGift": 4.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 29.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 22.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 21.0,
      "kosGift": 9.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 19.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 12.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 11.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 15.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 8.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 7.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 29.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 28.0,
      "kosGift": 9.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 26.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 19.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 18.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 22.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 15.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 14.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 41.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 34.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 33.0,
      "kosGift": 9.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 24.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 23.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 27.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 20.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 19.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 34.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 27.0,
      "kosGift": 10.0
    },
    {
      "bundle": "I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 26.0,
      "kosGift": 9.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 24.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 17.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 16.0,
      "kosGift": 6.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 20.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 13.0,
      "kosGift": 7.0
    },
    {
      "bundle": "I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 12.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상(MNP)",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 61.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 55.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 47.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 46.0,
      "kosGift": 9.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상(MNP)",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 53.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 47.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 39.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 38.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 40.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 32.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상(MNP)",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 66.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 60.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 52.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 51.0,
      "kosGift": 9.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상(MNP)",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 58.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 52.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 44.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 43.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 45.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 37.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상(MNP)",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 59.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 53.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 45.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 44.0,
      "kosGift": 9.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상(MNP)",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 51.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 45.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 37.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 38.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 30.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 29.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상(MNP)",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 54.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 48.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 40.0,
      "kosGift": 10.0
    },
    {
      "bundle": "M+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 39.0,
      "kosGift": 9.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상(MNP)",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 46.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 40.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 32.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 6.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 33.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 25.0,
      "kosGift": 7.0
    },
    {
      "bundle": "M+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 24.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 50.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 35.0,
      "kosGift": 9.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 45.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 29.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 31.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 23.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 21.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 57.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 43.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 42.0,
      "kosGift": 9.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 52.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 38.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 38.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 30.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 28.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 62.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 48.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 47.0,
      "kosGift": 9.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 57.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 43.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 41.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 43.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 35.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "Y",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 33.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 55.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 41.0,
      "kosGift": 10.0
    },
    {
      "bundle": "U+I+T",
      "internet": "에센스",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 40.0,
      "kosGift": 9.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 50.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "베이직",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 34.0,
      "kosGift": 6.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "모든G 이상",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 36.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "에센스/플러스",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 28.0,
      "kosGift": 7.0
    },
    {
      "bundle": "U+I+T",
      "internet": "슬림플러스↓",
      "tv": "라이트/베이직",
      "onestop": "N",
      "genie3": "Y",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 26.0,
      "kosGift": 6.0
    },
    {
      "bundle": "구분",
      "internet": "nan",
      "tv": "요금제",
      "onestop": "가입 유형",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 90.0,
      "kosGift": 37.0
    },
    {
      "bundle": "무선구간",
      "internet": "nan",
      "tv": "5G/LTE 요금제",
      "onestop": "MNP",
      "genie3": "N",
      "basePolicy": null,
      "comboPolicy": null,
      "totalPolicy": 28.0,
      "kosGift": 13.0
    }
  ]
};